pub mod assist;
pub mod decontaminate;
pub mod eml;
pub mod graph;
pub mod groups;
pub mod inbox;
pub mod interceptor;
pub mod link_titles;
pub mod llm;
pub mod mail;
pub mod mail_view;
pub mod parser;
pub mod preview;
pub mod source;
pub mod watcher;

pub use decontaminate::decontaminate_email_body;
pub use interceptor::{intercept_volatile_urls, make_manual_slug};
pub use llm::{LlmClient, LlmJob, LlmParseResult};
pub use mail::{AttachmentMeta, InboundMail};
pub use parser::{parse, ParsedEmail, ParserConfig};
pub use source::{MailHealth, MailOutcome, MailSource};
pub use watcher::EmailWatcher;
